CREATE SCHEMA IF NOT EXISTS staging;

-- =====================================================
-- RAW: append-only, order_id có thể duplicate
-- PostgreSQL
-- =====================================================

CREATE TABLE IF NOT EXISTS staging.stg_inform_ecom_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    order_id VARCHAR(50) NOT NULL,
    rso_name VARCHAR(50) NULL,
    channel VARCHAR(20) NOT NULL,
    customer_id VARCHAR(50) NULL,
    customer_name VARCHAR(100) NULL,
    order_flag VARCHAR(30) NULL,

    deadline TIMESTAMP NULL,
    delivery_at TIMESTAMP NULL,
    fulfillment_at TIMESTAMP NULL,
    complete_at TIMESTAMP NULL,
    cancel_at TIMESTAMP NULL,

    status SMALLINT NOT NULL DEFAULT 0,
    ps_status VARCHAR(150) NULL,
    picking_status SMALLINT NULL,
    picking_name VARCHAR(50) NULL,

    total_items INTEGER NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    net_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,

    address_shipping VARCHAR(255) NOT NULL,
    phone_shipping VARCHAR(100) NOT NULL,

    customer_note VARCHAR(500) NULL,
    packing_note VARCHAR(500) NULL,

    repick_stt SMALLINT NULL,
    repick_note TEXT NULL,

    shipping_carrier VARCHAR(255) NULL,

    cron_handle_detail VARCHAR(20) NOT NULL DEFAULT 'uncheck',

    uic_id INTEGER NULL,
    uic_name VARCHAR(255) NULL,

    get_by VARCHAR(255) NOT NULL,
    warehouse VARCHAR(50) NOT NULL DEFAULT 'WH-PS',

    location_id INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NULL,
    updated_id INTEGER NULL,

    package_code VARCHAR(50) NULL,

    CONSTRAINT pk_stg_inform_ecom_order
        PRIMARY KEY (id)
);


-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON COLUMN staging.stg_inform_ecom_order.delivery_at
IS 'Ngày xuất kho';

COMMENT ON COLUMN staging.stg_inform_ecom_order.fulfillment_at
IS 'Ngày đóng gói';

COMMENT ON COLUMN staging.stg_inform_ecom_order.complete_at
IS 'Ngày giao thành công';

COMMENT ON COLUMN staging.stg_inform_ecom_order.repick_stt
IS '1 - Chưa xử lý / 2 - Đã xử lý';

COMMENT ON COLUMN staging.stg_inform_ecom_order.cron_handle_detail
IS 'dùng để băm nhỏ chi tiết đơn hàng';


-- =====================================================
-- INDEX
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_stg_inform_ecom_order_order_id
ON staging.stg_inform_ecom_order (order_id);